/* TO BE DELETED */
/* SHOULD BE AUTOGENERATED */
#include <vnet/cdb/cdb.h>
#include "unat_gen.h"
#include <vnet/format_fns.h>
#include <arpa/inet.h>
#include "unat.h"
#include <vlib/vlib.h>
#include <vppinfra/clib_error.h>
#include <assert.h>

struct json_object *
unat_cfg_pool_interface_tojson (cdb_inode_t *dir, void *data)
{
  char *cfg = data;
  return json_object_new_string(cfg);
}

struct json_object *
unat_cfg_interfaces_tojson (cdb_inode_t *dir, void *data)
{
  u64 cfg = *(u64 *)data;
  return json_object_new_boolean(cfg);
}

static void
unat_cfg_free (void *data)
{
  vec_free(data);
}

struct json_object *
unat_cfg_parameters_tojson (cdb_inode_t *dir, void *data)
{
  unat_cfg_params_t *cfg = data;
  struct json_object *json = json_object_new_object();
  json_object_object_add(json, "max-sessions",
			 json_object_new_int64(cfg->max_sessions));
  json_object_object_add(json, "icmp-timeout",
			 json_object_new_int64(cfg->icmp_timeout));
  json_object_object_add(json, "udp-timeout",
			 json_object_new_int64(cfg->udp_timeout));
  json_object_object_add(json, "tcp-transitory-timeout",
			 json_object_new_int64(cfg->tcp_transitory_timeout));
  json_object_object_add(json, "tcp-established-timeout",
			 json_object_new_int64(cfg->tcp_established_timeout));
  json_object_object_add(json, "default-timeout",
			 json_object_new_int64(cfg->default_timeout));
  return json;
}

static void
unat_cfg_pool_interface_copy (cdb_inode_t *dst, cdb_inode_t *src)
{
  clib_warning("In copy");
  assert (dst && src);
  char *v = src->data;

  dst->data = vec_dup(v);
}

static void
unat_cfg_parameters_copy (cdb_inode_t *dst, cdb_inode_t *src)
{

  clib_warning("In copy");
  assert (dst && src);
  unat_cfg_params_t *v = src->data;

  dst->data = vec_dup(v);
}

static void
unat_cfg_pool_prefix_copy (cdb_inode_t *dst, cdb_inode_t *src)
{
  clib_warning("In copy");
  assert (dst && src);
  unat_cfg_pool_t *v = src->data;

  dst->data = vec_dup(v);
}

struct json_object *
unat_cfg_pool_prefix_tojson (cdb_inode_t *dir, void *data)
{
  unat_cfg_pool_t *c, *cfg = data; /* Vector of pools */

  struct json_object *json = 0;
  if (vec_len(cfg)) {
    json = json_object_new_array();
  }
  vec_foreach (c, cfg) {
    struct json_object *e = json_object_new_object();
    json_object_object_add(e, "prefixlen",
			   json_object_new_int64(c->prefixlen));
    json_object_object_add(e, "vrf-id",
			   json_object_new_int64(c->vrf_id));
    u8 *s = format(0, "%U%c", format_ip4_address, &c->prefix, 0);
    json_object_object_add(e, "prefix",
			   json_object_new_string((char *)s));
    vec_free(s);
    json_object_array_add(json, e);
  }

  return json;
}

static void
unat_cfg_pool_prefix_fromjson (u32 index, char **path, struct json_object *json)
{
  unat_main_t *um = &unat_main;
  int i;
  unat_cfg_pool_t cfg;
  struct json_object *val;

  int l = json_object_array_length(json);
  if (!l) return;

  cdb_inode_t *d = cdb_lookup_index_path(index, path);
  unat_cfg_pool_t *cfgvec = d ? d->data : 0;

  for (i = 0; i < l; i++) {
    json_object *obj = json_object_array_get_idx(json, i);
    if (json_object_object_get_ex(obj, "prefixlen", &val))
      cfg.prefixlen = json_object_get_int64(val);
    if (json_object_object_get_ex(obj, "vrf-id", &val))
      cfg.vrf_id = json_object_get_int64(val);
    if (json_object_object_get_ex(obj, "prefix", &val))
      inet_pton(AF_INET, json_object_get_string(val), &cfg.prefix);
    vec_add1(cfgvec, cfg);
  }
  cdb_set_pointer_path(index, um->pool_prefix_index, path, cfgvec);
}

static void
unat_cfg_interfaces_fromjson (u32 index, char **path, struct json_object *json)
{
  json_object_object_foreach(json, key, val) {
    vec_add1(path, key);
    cdb_set_inline_path(index, path, json_object_get_boolean(val));
    vec_pop(path);
  }
}

static void
unat_cfg_pool_interface_fromjson (u32 index, char **path, struct json_object *json)
{
  unat_main_t *um = &unat_main;
  cdb_inode_t *d = cdb_lookup_index_path(index, path);
  char *s = 0;

  if (d && d->data)
    vec_free(d->data);

  s = (char *)format(0, "%s", json_object_get_string(json));
  cdb_set_pointer_path(index, um->pool_interface_index, path, s);
}

static void
unat_cfg_parameters_fromjson (u32 index, char **path, struct json_object *json)
{
  unat_main_t *um = &unat_main;
  unat_cfg_params_t cfg = { .max_sessions = UNAT_DEFAULT_MAX_SESSIONS,
			    .default_timeout = UNAT_DEFAULT_TIMEOUT,
			    .icmp_timeout = UNAT_DEFAULT_TIMEOUT_ICMP,
			    .udp_timeout = UNAT_DEFAULT_TIMEOUT_UDP,
			    .tcp_transitory_timeout = UNAT_DEFAULT_TIMEOUT_TCP_TRANSITORY,
			    .tcp_established_timeout = UNAT_DEFAULT_TIMEOUT_TCP_ESTABLISHED,
  };
  struct json_object *val;

  if (json_object_object_get_ex(json, "max-sessions", &val))
    cfg.max_sessions = json_object_get_int64(val);
  if (json_object_object_get_ex(json, "default-timeout", &val))
    cfg.default_timeout = json_object_get_int64(val);
  if (json_object_object_get_ex(json, "icmp-timeout", &val))
    cfg.icmp_timeout = json_object_get_int64(val);
  if (json_object_object_get_ex(json, "udp-timeout", &val))
    cfg.udp_timeout = json_object_get_int64(val);
  if (json_object_object_get_ex(json, "tcp-transitory-timeout", &val))
    cfg.tcp_transitory_timeout = json_object_get_int64(val);
  if (json_object_object_get_ex(json, "tcp-established-timeout", &val))
    cfg.tcp_established_timeout = json_object_get_int64(val);

  cdb_inode_t *d = cdb_lookup_index_path(index, path);
  if (d && d->data)
    vec_free(d->data);
  
  unat_cfg_params_t *cfgvec = 0;
  vec_add1(cfgvec, cfg);
  cdb_set_pointer_path(index, um->parameters_index, path, cfgvec);
}

clib_error_t *
unat_gen_init (vlib_main_t * vm)
{
  unat_main_t *um = &unat_main;
  /*
   * TO BE AUTOGENERATED
   * Register configuration handlers 
   */
  {
    cdb_types_t t = { .tojson = unat_cfg_pool_interface_tojson,
		      .fromjson = unat_cfg_pool_interface_fromjson,
		      .copy = unat_cfg_pool_interface_copy,
		      .free = unat_cfg_free };
    um->pool_interface_index = cdb_register_type(&t);
  }
  {
    cdb_types_t t = { .tojson = unat_cfg_pool_prefix_tojson,
		      .fromjson = unat_cfg_pool_prefix_fromjson,
		      .free = unat_cfg_free,
    		      .copy = unat_cfg_pool_prefix_copy };
    um->pool_prefix_index = cdb_register_type(&t);
  }
  {
    cdb_types_t t = { .tojson = unat_cfg_interfaces_tojson,
		      .fromjson = unat_cfg_interfaces_fromjson,
		      .free = unat_cfg_free };
    um->interfaces_index = cdb_register_type(&t);
  }
  {
    cdb_types_t t = { .tojson = unat_cfg_parameters_tojson,
		      .fromjson = unat_cfg_parameters_fromjson,
		      .free = unat_cfg_free,
		      .copy = unat_cfg_parameters_copy };
    um->parameters_index = cdb_register_type(&t);
  }

  cdb_register_path("/unat/parameters", um->parameters_index);
  cdb_register_path("/unat/interfaces", um->interfaces_index);
  cdb_register_path("/unat/pool/prefix", um->pool_prefix_index);
  cdb_register_path("/unat/pool/interface", um->pool_interface_index);

  return 0;
}

VLIB_INIT_FUNCTION (unat_gen_init) =
{
 .runs_after = VLIB_INITS("cdb_init"),
};
