/****
 * TO BE AUTOGENERATED:
 */

/*
 * Confguration entries
 */
#include "unat.h"
#include <vnet/ip/ip4_packet.h>
typedef struct {
  ip4_address_t prefix;
  u8 prefixlen;
  u32 vrf_id;
} unat_cfg_pool_t;

typedef struct {
  u32 max_sessions;
#define _(n) \
  u32 n##_timeout;
  foreach_unat_timers
#undef _
} unat_cfg_params_t;

